services:
  backend:
    build: .
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./config/.env.dev
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/.env.dev.db
  redis:
    image: redis
  worker:
    build: .
    volumes:
      - ./backend/:/usr/src/backend/
    env_file:
      - ./config/.env.dev
    command: celery --workdir=./backend -A base worker -l INFO

volumes:
  postgres_data:
